spring:
  datasource:
    password: Subha99@
    username: root

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
